- name: create ec2 and r53 records
  hosts: localhost
  connection: local
  vars:
    # subnet_id: "subnet-0959de57b0ad6410f"
    # sg_id: "sg-0bdc6d5500f2d30d5"
    ami_id: "ami-0220d79f3f480ecf5"
    instances:
    - { name: 'frontend', tier: 'Expance-Public', sg_id: "{{ Public.group_id }}" }
    - { name: 'backend',  tier: 'Expance-Private', sg_id: "{{ Private.group_id }}" }
    - { name: 'mysql', tier: 'Expance-DB', sg_id: "{{ DB.group_id }}" }
    - mysql
    - backend
    - frontend
    zone: daws98.store
  tasks:
  - name: ansible to install boto3 and botocore
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      executable: pip3.9

  - name: Launch EC2 Instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      region: "{{ region }}"
      image_id: "{{ image_id }}"
      instance_type: "{{ instance_type }}"
      vpc_subnet_id: "{{ (subnets_config.results | selectattr('item.tier', 'equalto', item.tier) | first).subnet.id }}"
      security_group: "{{ item.sg_id }}"
      wait: yes
      tags:
        Tier: "{{ item.tier }}"
    loop:"{{ instance }}"
    register: ec2_instances
     
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances

  # - name: print the output
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_instances }}"

  #private IP R53
  - name: create r53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" #mysql.daws81s.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"

  - name: create r53 public record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}" #daws81s.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"
    when: item.item == "frontend" #when keyword should not have {{}}


