- name: create VPC
  hosts: localhost
  connection: local
  vars:             # Define regions and their corresponding CIDR blocks to avoid overlaps
    regions:
      - { name: 'us-east-1a', vpc_cidr: '10.1.0.0/16', web: '10.1.1.0/24', app: '10.1.2.0/24', db: '10.1.3.0/24' }
      - { name: 'us-east-1b', vpc_cidr: '10.2.0.0/16', web: '10.2.1.0/24', app: '10.2.2.0/24', db: '10.2.3.0/24' }

  tasks:
    - name: ansible to install boto3 and botocore
      ansible.builtin.pip:
        name:
        - boto3
        - botocore
        executable: pip3.9
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: my-vpc
        cidr_block: 10.0.0.0/16
        region: us-east-1
      register: vpc
    # - name: print the output
    #   ansible.builtin.debug:
    #     msg: "{{ vpc }}"
    - name: Create and attach Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"  # Use the ID registered from the VPC creation task
        state: present
        tags:
          Name: my-igw
      register: igw
    # - name: print the output
    #   ansible.builtin.debug:
    #     msg: "{{ igw }}"  
    - name: Create VPC in each region
      amazon.aws.ec2_vpc_net:
        name: "3-tier-vpc-{{ item.name }}"
        cidr_block: "{{ item.vpc_cidr }}"
        region: "{{ item.name }}"
      loop: "{{ regions }}"
      register: vpcs
    - name: Create 3-Tier Subnets in each region
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ item.1.vpc.id }}"
        region: "{{ item.0.name }}"
        az: "{{ item.0.name }}a"
        cidr: "{{ item.0[item.2] }}"
        tags:
          Name: "{{ item.2 | capitalize }}-Subnet-{{ item.0.name }}"
          Tier: "{{ item.2 | capitalize }}"
      # Loops through regions, matched VPC IDs, and the 3 tiers
      with_nested:
        - "{{ regions }}"
        - "{{ vpcs.results }}"
        - [ 'web', 'app', 'db' ]
      when: item.0.name == item.1.item.name
