- name: create VPC, igw, subnets, Route Tables, Security group
  hosts: localhost
  connection: local
  vars: 
    vpc_id: "{{ vpc.vpc.id }}"
    igw_id: "{{ igw.gateway_id }}"          
    region: us-east-1
    # Define the tiers and zones mapping
    subnets_config:
      - { tier: 'Expance-Public', az: 'a', cidr: '10.0.1.0/24', public: yes }
      - { tier: 'Expance-Private', az: 'a', cidr: '10.0.2.0/24', public: no }
      - { tier: 'Expance-DB',  az: 'a', cidr: '10.0.3.0/24', public: no }
      - { tier: 'Expance-Public', az: 'b', cidr: '10.0.4.0/24', public: yes }
      - { tier: 'Expance-Private', az: 'b', cidr: '10.0.5.0/24', public: no }
      - { tier: 'Expance-DB',  az: 'b', cidr: '10.0.6.0/24', public: no }
  tasks:
    - name: ansible to install boto3 and botocore
      ansible.builtin.pip:
        name:
        - boto3
        - botocore
        executable: pip3.9

    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: Expance
        cidr_block: 10.0.0.0/16
        region: us-east-1
      register: vpc

    # - name: print the output
    #   ansible.builtin.debug:
    #     msg: "{{ vpc }}"

    - name: Create and attach Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"  # Use the ID registered from the VPC creation task
        state: present
        tags:
          Name: Expance-igw
      register: igw

    # - name: print the output
    #   ansible.builtin.debug:
    #     msg: "{{ igw }}"  
      
    - name: Create 6 Subnets for 3-Tier Architecture
      amazon.aws.ec2_vpc_subnet:
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        az: "{{ region }}{{ item.az }}"
        cidr: "{{ item.cidr }}"
        map_public: "{{ item.public }}"
        tags:
          Name: "{{ item.tier | capitalize }}-{{ item.az }}"
          Tier: "{{ item.tier }}"
      loop: "{{ subnets_config }}"
      register: subnets_config

    # - name: print the output
    #   ansible.builtin.debug:
    #     msg: "{{ subnets_config }}"  

    - name: Create Public Route Table (Expance public )
      amazon.aws.ec2_vpc_route_table:
          vpc_id: "{{ vpc_id }}"
          region: "{{ region }}"
          tags:
            Name: Public
          subnets: "{{ subnets_config.results | selectattr('item.tier', 'equalto', 'Expance-Public') | map(attribute='subnet.id') | list }}"
          routes:
            - dest: 0.0.0.0/0
              gateway_id: "{{ igw_id }}"
      register: Public
  
    - name: Create Private Route Table (Expance Private & Expance DB)
      amazon.aws.ec2_vpc_route_table:
          vpc_id: "{{ vpc_id }}"
          region: "{{ region }}"
          tags:
            Name: Private
          subnets: "{{ subnets_config.results | rejectattr('item.tier', 'equalto', 'Expance-Public') | map(attribute='subnet.id') | list }}"
      register: Private
         
    - name: Create Expance Public Security Group
      amazon.aws.ec2_security_group:
        name: Public
        description: Allow HTTP from everywhere
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: Public

    - name: Create Expance Private Security Group
      amazon.aws.ec2_security_group:
        name: Private
        description: Allow traffic from Web Tier
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 8080 # Adjust based on your app port
            to_port: 8080
            group_id: "{{ Public.group_id }}" # Links to Web SG
      register: Private

    - name: Create Expance Database Security Group
      amazon.aws.ec2_security_group:
        name: DB
        description: Allow traffic from App Tier
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 3306 # MySQL/Aurora port
            to_port: 3306
            group_id: "{{ Private.group_id }}" # Links to App SG
      register: DB

    - name: Allocate Elastic IP for NAT Gateway
      amazon.aws.ec2_eip:
        region: "{{ region }}"
        state: present
        reuse_existing_ip_allowed: yes
        # Search for an existing EIP with this tag
        tag_name: Name
        tag_value: Expance-NAT-EIP
        tags:
          Name: Expance-NAT-EIP
      register: nat_eip

    - name: Create NAT Gateway in a Public Subnet
      amazon.aws.ec2_vpc_nat_gateway:
        region: "{{ region }}"
        # Selects the first subnet marked as public from the created subnets
        subnet_id: "{{ (subnets_config.results | selectattr('item.public', 'equalto', True) | first).subnet.id }}"
        allocation_id: "{{ nat_eip.allocation_id }}"
        wait: yes
        if_exist_do_not_create: yes
      register: nat_gw

    - name: Update Private Route Table with NAT Gateway
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: Private
        # Re-associates all non-public subnets
        subnets: "{{ subnets_config.results | rejectattr('item.tier', 'equalto', 'Expance-Public') | map(attribute='subnet.id') | list }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ nat_gw.nat_gateway_id }}"

    # - name: Create NAT Gateway in a Public Subnet
    #   amazon.aws.ec2_vpc_nat_gateway:
    #     region: "{{ region }}"
    #     subnet_id: "{{ subnets_config.results | selectattr('item.Public', 'equalto', true) | map(attribute='subnet.id') | first }}"
    #     allocation_id: "{{ nat_eip.allocation_id }}"
    #     wait: yes
    #     if_exist_do_not_create: yes  # This is the key for idempotency
    #     tags:
    #       Name: "Expance-NAT-Gateway"
    #   register: nat_gw
  
    # - name: Update Private Route Table with NAT Gateway
    #   amazon.aws.ec2_vpc_route_table:
    #     vpc_id: "{{ vpc_id }}"
    #     region: "{{ region }}"
    #     lookup: tag
    #     tags:
    #       Name: Expance Private
    #     subnets: "{{ subnets_config.results | rejectattr('item.tier', 'equalto', 'Public') | map(attribute='subnet.id') | list }}"
    #     routes:
    #       - dest: 0.0.0.0/0
    #         gateway_id: "{{ nat_gw.nat_gateway_id }}"

