- name: create ec2 and r53 records
  hosts: localhost
  connection: local
  vars:
    ami_id: "ami-0220d79f3f480ecf5"
    region: "us-east-1" # Make sure this is defined
    instance_type: "t3.micro"
    instances:
      - { name: 'frontend', tier: 'Expance-Public', sg_id: "{{ Public_sg }}" }
      - { name: 'backend',  tier: 'Expance-Private', sg_id: "{{ Private_sg }}" }
      - { name: 'mysql', tier: 'Expance-DB', sg_id: "{{ DB_sg }}" }
    zone: daws98.store

  tasks:
    - name: Get all subnets for the VPC
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters:
          vpc-id: "vpc-0da46496d0678ab8b"
      register: subnets_info

    - name: Get Security Group info
      amazon.aws.ec2_security_group_info:
        filters:
          group-name: 
            - "Public"   # Change these to match your actual SG names
            - "Private"
            - "DB"
      register: sg_info

    - name: Set SG facts
      set_fact:
        Public_sg: "{{ sg_info.security_groups | selectattr('group_name', 'equalto', 'Public') | map(attribute='group_id') | first }}"
        Private_sg: "{{ sg_info.security_groups | selectattr('group_name', 'equalto', 'Private') | map(attribute='group_id') | first }}"
        DB_sg: "{{ sg_info.security_groups | selectattr('group_name', 'equalto', 'DB') | map(attribute='group_id') | first }}"

    - name: Launch EC2 Instances
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        region: "{{ region }}"
        image_id: "{{ ami_id }}"
        instance_type: "{{ instance_type }}"
        vpc_subnet_id: "{{ subnets_info.subnets | selectattr('tags.Tier', 'equalto', item.tier) | map(attribute='id') | first }}"
        security_group: "{{ item.sg_id }}"
        wait: yes
        tags:
          Tier: "{{ item.tier }}"
      loop: "{{ instances }}"
      register: ec2_instances

      
  # - name: print the output
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_instances }}"

  #private IP R53
  # - name: create r53 private records
  #   amazon.aws.route53:
  #     state: present
  #     zone: "{{ zone }}"
  #     record: "{{ item.item }}.{{ zone }}" #mysql.daws81s.online
  #     type: A
  #     ttl: 1
  #     value: "{{ item.instances[0].private_ip_address }}"
  #     wait: true
  #     overwrite: true
  #   loop: "{{ ec2_instances.results }}"

  # - name: create r53 public record for frontend
  #   amazon.aws.route53:
  #     state: present
  #     zone: "{{ zone }}"
  #     record: "{{ zone }}" #daws81s.online
  #     type: A
  #     ttl: 1
  #     value: "{{ item.instances[0].public_ip_address }}"
  #     wait: true
  #     overwrite: true
  #   loop: "{{ ec2_instances.results }}"
  #   when: item.item == "frontend" #when keyword should not have {{}}


