[mysql]
mysql.daws98.store 

[backend]
backend.daws98.store

[frontend]
frontend.daws98.store

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[hosts]
localhost

# [frontend]
# frontend_host ansible_host=44.198.52.7

# [backend]
# backend_host ansible_host=10.0.2.164

# [mysql]
# mysql_host ansible_host=10.0.6.140

# [all:vars]
# ansible_user=ec2-user
# ansible_ssh_private_key_file=/Users/ganeshmadda/Documents/devops/daws-81s/linux-key

# # This tells Ansible to use the frontend as a tunnel for backend and db
# [backend:vars]
# ansible_ssh_common_args='-o ProxyJump=ec2-user@44.198.52.7'

# [database:vars]
# ansible_ssh_common_args='-o ProxyJump=ec2-user@44.198.52.7'
